### ISSUE TITLE
The go version should be updated to v1.21

### ISSUE THREAD

**Issue by HighQualityWaschbaer** [Avanis-GmbH/shopware-kit#21]
Shopware kit should be updated to the most recent Go version.

**Comment by Valentin-Kaiser** [comment]
Why?

**Comment by Plaenkler** [comment]
Why not?

**Comment by Valentin-Kaiser** [comment]
Because there is no need?
Please provide a reasonable explanation, otherwise we can close the issue.

**Comment by Plaenkler** [comment]
I think it's always a good idea to update with 100% backwards compatibility. In Golang 1.20/1.21, many improvements were also made to the runtime and the compiler.
